#!/usr/bin/env bash
# tests/fleet-no-agent-names.test.sh
#
# fleet-ops#519: no agent names on Nish's work.
# Proves the real checker in bin/fleet-no-agent-names-check
# (and its Python lib) rejects the forbidden attribution patterns and
# accepts legitimate prose.
#
# Phase A: worker.md carries the rule and names the check.
# Phase B: PR body checks.
# Phase C: commit-message checks.
# Phase D: combined PR + commit range.

set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$here/.." && pwd)"
bin="$repo_root/bin/fleet-no-agent-names-check"
lib="$repo_root/lib/fleet-no-agent-names-check.py"
worker="$repo_root/prompts/worker.md"

fail() { echo "FAIL: $*" >&2; exit 1; }
ok()   { echo "OK: $*"; }

[[ -x "$bin" ]] || fail "missing or not executable: $bin"
[[ -f "$lib" ]] || fail "missing: $lib"
[[ -f "$worker" ]] || fail "missing: $worker"

scratch="$(mktemp -d -t no-agent-names.XXXXXX)"
trap 'rm -rf "$scratch"' EXIT INT TERM

# ============================================================================
# Phase A: worker prompt carries the rule and the binary
# ============================================================================
grep -qE "No agent names|Agent names are forbidden" "$worker" \
    || fail "worker.md must state the no-agent-names rule"
grep -F -- 'fleet-no-agent-names-check' "$worker" >/dev/null \
    || fail "worker.md must tell authors to run bin/fleet-no-agent-names-check"
grep -qE "Co-Authored-By|Co-authored-by" "$worker" \
    || fail "worker.md must forbid Co-Authored-By trailers"
grep -qE "Generated with|Generated with" "$worker" \
    || fail "worker.md must forbid Generated-with footers"
ok "A: worker.md carries the no-agent-names gate"

# ============================================================================
# Helpers
# ============================================================================
check_body() {
    local body="$1"
    local expect_reject="${2:-0}"
    printf '%s\n' "$body" >"$scratch/body.md"
    set +e
    out=$("$bin" --pr-body "$scratch/body.md" 2>&1)
    rc=$?
    set -e
    if [[ "$expect_reject" == "1" ]]; then
        [[ "$rc" == "1" ]] || fail "expected reject for: $body (rc=$rc out=$out)"
    else
        [[ "$rc" == "0" ]] || fail "expected pass for: $body (rc=$rc out=$out)"
    fi
}

# ============================================================================
# Phase B: PR body checks
# ============================================================================
check_body "Fix the thing.\n\nCloses #1" 0
ok "B1: plain PR body passes"

check_body "Co-Authored-By: Devin <devin@example.com>" 1
ok "B2: Co-Authored-By trailer is rejected"

check_body "Co-authored-by: nishfleet-worker[bot] <bot@example.com>" 1
ok "B3: lowercase Co-authored-by is rejected"

check_body "Summary\n\nGenerated with Devin" 1
ok "B4: Generated-with footer is rejected"

check_body "Summary\n\nGenerated by Claude" 1
ok "B5: Generated-by footer is rejected"

check_body "Summary\n\nGenerated using Grok" 1
ok "B6: Generated-using footer is rejected"

check_body "This fix was written by Claude" 1
ok "B7: 'by <agent>' attribution is rejected"

check_body "I used Devin for the first draft" 1
ok "B8: 'used <agent>' attribution is rejected"

check_body "We route via OpenAI for this lane" 1
ok "B9: 'via <agent>' attribution is rejected"

check_body "This PR updates the cursor rule" 0
ok "B10: mentioning an agent product without attribution word passes"

check_body "The sol and luna models are not in scope" 0
ok "B11: agent names in a list without attribution word pass"

# ============================================================================
# Phase C: commit message checks
# ============================================================================
git_repo="$scratch/repo"
mkdir -p "$git_repo"
cd "$git_repo"
git init -q
git config user.email "agent@example.com"
git config user.name "Test Agent"

printf 'initial commit\n' >file
git add file
git commit -q -m "initial commit"

git checkout -q -b feature
printf 'change\n' >file
git add file
# This commit would violate the rule if it ever reached a PR.
git commit -q -m "feat: add thing

Co-Authored-By: Claude <claude@example.com>
Generated with Devin"

set +e
out=$("$bin" --commit-range main...feature 2>&1)
rc=$?
set -e
[[ "$rc" == "1" ]] || fail "commit range with Co-Authored-By must reject (rc=$rc out=$out)"
[[ "$out" == *"Co-Authored-By"* ]] || fail "rejection must name Co-Authored-By"
[[ "$out" == *"Generated-with"* ]] || fail "rejection must name Generated-with"
ok "C1: commit range with forbidden trailers is rejected"

# Rewrite the branch with a clean commit.
rm -rf .git
ok "C2: temp repo cleaned up"

# Build a clean repo and branch for the combined test.
git init -q
git config user.email "agent@example.com"
git config user.name "Test Agent"
printf 'initial\n' >file
git add file
git commit -q -m "initial"
git checkout -q -b clean-feature
printf 'change\n' >file
git add file
git commit -q -m "feat: add thing

No agent attribution."

set +e
out=$("$bin" --commit-range main...clean-feature --pr-body "$scratch/body.md" 2>&1)
rc=$?
set -e
[[ "$rc" == "0" ]] || fail "clean commit + body must pass (rc=$rc out=$out)"
ok "C2: clean commit range passes"

cd "$here"

# ============================================================================
# Phase D: combined PR body + commit range
# ============================================================================
# The check must run against both inputs and report all problems.

git_repo2="$scratch/repo2"
mkdir -p "$git_repo2"
cd "$git_repo2"
git init -q
git config user.email "agent@example.com"
git config user.name "Test Agent"
printf 'initial\n' >file2
git add file2
git commit -q -m "initial"
git checkout -q -b combo-feature
printf 'change\n' >file2
git add file2
git commit -q -m "feat: add thing"

printf 'This was built by Claude\n' >"$scratch/bad-body.md"

set +e
out=$("$bin" --commit-range main...combo-feature --pr-body "$scratch/bad-body.md" 2>&1)
rc=$?
set -e
[[ "$rc" == "1" ]] || fail "bad body + clean commits must reject (rc=$rc out=$out)"
[[ "$out" == *"PR body"* ]] || fail "rejection must name PR body"
ok "D1: bad PR body with clean commits is rejected"

cd "$here"

echo "all phases passed"
