#!/usr/bin/env bash
# tests/fleet-no-agent-names.test.sh
#
# fleet-ops#519: no agent names on Nish's work.
# Proves the real checker in bin/fleet-no-agent-names-check
# (and its Python lib) rejects the forbidden attribution patterns and
# accepts legitimate prose.
#
# Phase A: worker.md carries the rule and names the check.
# Phase B: PR body checks.
# Phase C: commit-message checks.
# Phase D: combined PR + commit range.

set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$here/.." && pwd)"
bin="$repo_root/bin/fleet-no-agent-names-check"
lib="$repo_root/lib/fleet-no-agent-names-check.py"
worker="$repo_root/prompts/worker.md"

fail() { echo "FAIL: $*" >&2; exit 1; }
ok()   { echo "OK: $*"; }

[[ -x "$bin" ]] || fail "missing or not executable: $bin"
[[ -f "$lib" ]] || fail "missing: $lib"
[[ -f "$worker" ]] || fail "missing: $worker"

scratch="$(mktemp -d -t no-agent-names.XXXXXX)"
trap 'rm -rf "$scratch"' EXIT INT TERM

# ============================================================================
# Phase A: worker prompt carries the rule and the binary
# ============================================================================
grep -qE "No agent names|Agent names are forbidden" "$worker" \
    || fail "worker.md must state the no-agent-names rule"
grep -F -- 'fleet-no-agent-names-check' "$worker" >/dev/null \
    || fail "worker.md must tell authors to run bin/fleet-no-agent-names-check"
grep -qE "Co-Authored-By|Co-authored-by" "$worker" \
    || fail "worker.md must forbid Co-Authored-By trailers"
grep -qE "Generated with|Generated with" "$worker" \
    || fail "worker.md must forbid Generated-with footers"
ok "A: worker.md carries the no-agent-names gate"

# ============================================================================
# Helpers
# ============================================================================
check_body() {
    local body="$1"
    local expect_reject="${2:-0}"
    printf '%s\n' "$body" >"$scratch/body.md"
    set +e
    out=$("$bin" --pr-body "$scratch/body.md" 2>&1)
    rc=$?
    set -e
    if [[ "$expect_reject" == "1" ]]; then
        [[ "$rc" == "1" ]] || fail "expected reject for: $body (rc=$rc out=$out)"
    else
        [[ "$rc" == "0" ]] || fail "expected pass for: $body (rc=$rc out=$out)"
    fi
}

# ============================================================================
# Phase B: PR body checks
# ============================================================================
check_body "Fix the thing.\n\nCloses #1" 0
ok "B1: plain PR body passes"

check_body "Co-Authored-By: Devin <devin@example.com>" 1
ok "B2: Co-Authored-By trailer is rejected"

check_body "Co-authored-by: nishfleet-worker[bot] <bot@example.com>" 1
ok "B3: lowercase Co-authored-by is rejected"

check_body "Summary\n\nGenerated with Devin" 1
ok "B4: Generated-with footer is rejected"

check_body "Summary\n\nGenerated by Claude" 1
ok "B5: Generated-by footer is rejected"

check_body "Summary\n\nGenerated using Grok" 1
ok "B6: Generated-using footer is rejected"

check_body "This fix was written by Claude" 1
ok "B7: 'by <agent>' attribution is rejected"

check_body "I used Devin for the first draft" 1
ok "B8: 'used <agent>' attribution is rejected"

check_body "We route via OpenAI for this lane" 1
ok "B9: 'via <agent>' attribution is rejected"

check_body "This PR updates the cursor rule" 0
ok "B10: mentioning an agent product without attribution word passes"

check_body "The sol and luna models are not in scope" 0
ok "B11: agent names in a list without attribution word pass"

# ============================================================================
# Phase C: commit message checks
# ============================================================================
git_repo="$scratch/repo"
mkdir -p "$git_repo"
cd "$git_repo"
# Pin the initial branch name to `main` so the `--commit-range main...feature`
# check below finds a `main` ref. `git init` without `-b` follows the
# runner's `init.defaultBranch`, which is `master` on hosted GitHub Actions
# runners (Ubuntu 24.04 image) and `main` on the VPS. Pinning makes the
# test deterministic across both.
git init -q -b main
git config user.email "agent@example.com"
git config user.name "Test Agent"

printf 'initial commit\n' >file
git add file
git commit -q -m "initial commit"

git checkout -q -b feature
printf 'change\n' >file
git add file
# This commit would violate the rule if it ever reached a PR.
git commit -q -m "feat: add thing

Co-Authored-By: Claude <claude@example.com>
Generated with Devin"

set +e
out=$("$bin" --commit-range main...feature 2>&1)
rc=$?
set -e
[[ "$rc" == "1" ]] || fail "commit range with Co-Authored-By must reject (rc=$rc out=$out)"
[[ "$out" == *"Co-Authored-By"* ]] || fail "rejection must name Co-Authored-By"
[[ "$out" == *"Generated-with"* ]] || fail "rejection must name Generated-with"
ok "C1: commit range with forbidden trailers is rejected"

# Rewrite the branch with a clean commit.
rm -rf .git
ok "C2: temp repo cleaned up"

# Build a clean repo and branch for the combined test.
git init -q -b main
git config user.email "agent@example.com"
git config user.name "Test Agent"
printf 'initial\n' >file
git add file
git commit -q -m "initial"
git checkout -q -b clean-feature
printf 'change\n' >file
git add file
git commit -q -m "feat: add thing

No agent attribution."

set +e
out=$("$bin" --commit-range main...clean-feature --pr-body "$scratch/body.md" 2>&1)
rc=$?
set -e
[[ "$rc" == "0" ]] || fail "clean commit + body must pass (rc=$rc out=$out)"
ok "C2: clean commit range passes"

cd "$here"

# ============================================================================
# Phase D: combined PR body + commit range
# ============================================================================
# The check must run against both inputs and report all problems.

git_repo2="$scratch/repo2"
mkdir -p "$git_repo2"
cd "$git_repo2"
git init -q -b main
git config user.email "agent@example.com"
git config user.name "Test Agent"
printf 'initial\n' >file2
git add file2
git commit -q -m "initial"
git checkout -q -b combo-feature
printf 'change\n' >file2
git add file2
git commit -q -m "feat: add thing"

printf 'This was built by Claude\n' >"$scratch/bad-body.md"

set +e
out=$("$bin" --commit-range main...combo-feature --pr-body "$scratch/bad-body.md" 2>&1)
rc=$?
set -e
[[ "$rc" == "1" ]] || fail "bad body + clean commits must reject (rc=$rc out=$out)"
[[ "$out" == *"PR body"* ]] || fail "rejection must name PR body"
ok "D1: bad PR body with clean commits is rejected"

cd "$here"

# ============================================================================
# Phase E: origin/main..HEAD (asymmetric) vs origin/main...HEAD (symmetric)
# ============================================================================
# fleet-ops#944: a worker ran
#   fleet-no-agent-names-check --pr-body <body> --commit-range origin/main...HEAD
# `git log` with `...` is the SYMMETRIC DIFFERENCE: it lists commits in
# HEAD not in origin/main AND commits in origin/main not in HEAD. When
# origin/main has advanced with other PRs (each carrying legitimate
# Co-Authored-By trailers), the symmetric difference pulls those
# unrelated commits into the scan, producing a false REJECT on commits
# the worker never wrote. The correct range for "my PR's commits" is
# `origin/main..HEAD` (asymmetric: commits in HEAD not in origin/main).
#
# This test locks the contrast so a future worker.md that reverts to `...`
# is caught by CI, and so the check's own test suite proves the distinction.

git_repo3="$scratch/repo3"
mkdir -p "$git_repo3"
cd "$git_repo3"
git init -q -b main
git config user.email "agent@example.com"
git config user.name "Test Agent"
printf 'initial\n' >file3
git add file3
git commit -q -m "initial"

# Worker's own commit — clean, no attribution.
git checkout -q -b feature
printf 'change\n' >>file3
git add file3
git commit -q -m "feat: worker cleanup

No attribution here."

# Simulate origin/main advancing with a prior PR that shipped with a
# Co-Authored-By trailer (legitimate — that was another worker's PR).
# The worker's branch does NOT contain this commit.
git checkout -q main
printf 'remote\n' >>file3
git add file3
commit_args="feat: remote PR merged to main

Co-Authored-By: nishfleet-worker[bot] <bot@example.com>"
git -c "user.email=agent@example.com" -c "user.name=Test Agent" \
  commit -q -F - <<<"$commit_args"

# --- E1. `main...feature` (symmetric) is a FALSE POSITIVE on diverged main --
# The symmetric difference includes the main commit (which has a
# Co-Authored-By trailer from a prior PR). The check REJECTs — but that
# commit was not written by the current worker, so this is a false alarm.
# This reproduces the #944 incident: the worker got a REJECT on commits
# it did not author.
set +e
out=$("$bin" --pr-body "$scratch/body.md" --commit-range main...feature 2>&1)
rc=$?
set -e
[[ "$rc" == "1" ]] || fail "symmetric diff should REJECT (got rc=$rc out=$out) — the main commit's trailer leaks in"
[[ "$out" == *"Co-Authored-By"* ]] || fail "symmetric diff must surface the unrelated main commit's trailer"
ok "E1: origin/main...HEAD (symmetric) is a false positive when main diverged (#944 reproduced)"

# --- E2. `main..feature` (asymmetric) checks only the worker's own commits --
# The asymmetric range lists only commits in feature not in main — i.e.,
# the worker's own commit, which is clean. The check passes. This is the
# correct range worker.md now instructs.
set +e
out=$("$bin" --pr-body "$scratch/body.md" --commit-range main..feature 2>&1)
rc=$?
set -e
[[ "$rc" == "0" ]] || fail "asymmetric diff should pass (got rc=$rc out=$out) — the worker's own commit is clean"
ok "E2: origin/main..HEAD (asymmetric) checks only the worker's own commits, no false positive (#944 fix verified)"

# --- E3. contrast: worker's own commit with a trailer must still REJECT ----
# Proves the `..` fix does not suppress real attribution in the worker's
# own commits — only unrelated main commits are excluded.
git checkout -q feature
git -c "user.email=agent@example.com" -c "user.name=Test Agent" commit -q \
  --amend -m "feat: worker cleanup

Co-Authored-By: claude <claude@example.com>"
set +e
out=$("$bin" --pr-body "$scratch/body.md" --commit-range main..feature 2>&1)
rc=$?
set -e
[[ "$rc" == "1" ]] || fail "asymmetric diff must REJECT when worker's own commit has a trailer (rc=$rc out=$out)"
ok "E3: origin/main..HEAD still catches the worker's own Co-Authored-By trailer (no suppression of real hits)"

cd "$here"

echo "all phases passed"
